services:
  db:
    image: postgres:15
    container_name: franklin_db
    environment:
      POSTGRES_DB: franklin_db
      POSTGRES_USER: franklin_user
      POSTGRES_PASSWORD: franklin_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U franklin_user -d franklin_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: franklin_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://franklin_user:franklin_pass@db:5432/franklin_db

volumes:
  postgres_data: