# Generated by Django 4.2.7 on 2025-09-28 08:56

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_rating_to_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0)
                ],
                help_text='User rating (1-5 stars, null for imported reviews)'
            ),
        ),
    ]
